[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

monitor_speed = 115200

upload_protocol = esptool
upload_port = /dev/ttyUSB2
monitor_port = /dev/ttyUSB2

monitor_dtr = 0
monitor_rts = 0
monitor_filters = direct
; Remove: monitor_raw = yes

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio

build_flags =
  -Wall
  -Wextra
  -Werror=return-type
  -Wno-unused-parameter
  -O2
  -g2